### ISSUE TITLE
Speaker notes does not start timer from toolbar

### ISSUE THREAD

**Issue by zarthross** [denehyg/reveal.js-toolbar#3]
Using version 3.6.0 of Reveal JS and version 0.1.4 of 'reveal.js-toolbar'.

When I start the speaker notes with a running server (`npm start`) and I use the toolbar to open the speaker notes the timer does not start and the time stays '0:00am'.

Pressing the 's' key on the keyboard opens the speaker notes and the timer and time works as expected.

**Comment by denehyg** [comment]
This has been fixed in v0.1.5
