### ISSUE TITLE
Fullscreen Button not working

### ISSUE THREAD

**Issue by mragg** [denehyg/reveal.js-toolbar#5]
On Chrome und Chromium the Fullscreen-Button is not working. I'm getting an error-message in the console-view:
Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
    at Object.request (screenfull.min.js:7)
    at Object.toggle (screenfull.min.js:7)
    at toolbar.js:99
    at HTMLAnchorElement.button.onclick (toolbar.js:77)

There seem s.th. change with the fullscreen-api in Chrome last year (?)

**Comment by mfmcc1** [comment]
I updated my local version of screenfull.min.js (link below) and fullscreen button functionality works again. 

[https://github.com/sindresorhus/screenfull.js]()

**Comment by mragg** [comment]
That's it!
Thanks a lot, Fullscreen is working fine again :-)
Perhaps s.one can check in the new version of the screenfull.min.js .. could help new reveal users

**Comment by denehyg** [comment]
I've updated the screenfull version and released the plugin as v0.2.0. Let me know if there are still issues.
