### ISSUE TITLE
Uncaught ReferenceError: head is not defined

### ISSUE THREAD

**Issue by maxbraun** [denehyg/reveal.js-toolbar#6]
Hi!
running the plugin with the current version of reveal.js (3.8) causes a Reference Error:

> toolbar.js:41 Uncaught ReferenceError: head is not defined
    at loadPlugin (toolbar.js:41)
    at HTMLLinkElement.finish (toolbar.js:210)

Not 100% why, but does the plugin rely on head.js, which has been removed from reveal.js?

**Comment by denehyg** [comment]
Oops, thanks for picking this up. I was still testing against 3.7.0. I've pushed an update to remove the head.js dependency and released as v0.2.1.

**Comment by maxbraun** [comment]
Hey @denehyg,

thanks for the update. When not having the menu as dependency, loading of the toolbar fails (JS Error) as well with loaded menu (no js error).

Do you need more information from my side?

**Comment by denehyg** [comment]
If you set the option `captureMenu: false` the plugin won't look for the menu and should work fine.

The plugin was originally intended as an extension to the menu plugin and thus assumes it will be there by default. The above option remove the need for the menu to be present entirely, but admittedly this is not so obvious in the docs.
